{"uuid": "fe9874db-3cf2-4c28-b344-ffe11802d786", "children": ["55547bca-a6ce-4eea-b6b1-11f809cfa2e2"], "befores": [{"name": "_xunit_setup_class_fixture_TestCreateCourier", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'append'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/python.py\", line 856, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/python.py\", line 777, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/almihalev/yandex/practicum_qa_python_sprints/Sprint_7_qa_python/tests/test_list_of_orders.py\", line 16, in setup_class\n    cls.data.append(order)\n    ^^^^^^^^^^^^^^^\n"}, "start": 1701261853027, "stop": 1701261853080}], "start": 1701261853027, "stop": 1701261853089}